# Generated by Django 4.1 on 2022-08-17 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentDetail',
            new_name='UserDetail',
        ),
    ]
